# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.14.0rc1-slim-bullseye
RUN pip install uv

WORKDIR /app
COPY . /app

RUN uv venv
RUN uv pip install .

EXPOSE 8000

# Set default command to run the MCP server
CMD ["bash", "-c", "uv run mcp run --transport streamable-http ./main.py"]
